"""Phase 1 baseline: settings, secrets, runs, rate_limit_counters.

Revision ID: 0001_initial
Revises:
Create Date: 2026-04-11

Hand-authored rather than autogenerated because the async engine setup in
app/db/base.py makes ``alembic revision --autogenerate`` awkward on a fresh
database. Every column here mirrors ``app/db/models.py`` verbatim.
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # settings: single-row table (id fixed at 1 by application convention).
    op.create_table(
        "settings",
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column("kill_switch", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("dry_run", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("daily_cap", sa.Integer(), nullable=False, server_default=sa.text("20")),
        sa.Column("delay_min_seconds", sa.Integer(), nullable=False, server_default=sa.text("30")),
        sa.Column("delay_max_seconds", sa.Integer(), nullable=False, server_default=sa.text("120")),
        sa.Column("timezone", sa.String(), nullable=False, server_default=sa.text("'UTC'")),
        sa.Column("wizard_complete", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("keywords_csv", sa.Text(), nullable=False, server_default=sa.text("''")),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.current_timestamp(),
        ),
    )

    # secrets: Fernet-encrypted credential store. No plaintext column.
    op.create_table(
        "secrets",
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.current_timestamp(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.current_timestamp(),
        ),
    )
    op.create_index("ix_secrets_name", "secrets", ["name"], unique=True)

    # runs: one row per scheduled or forced pipeline execution.
    op.create_table(
        "runs",
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.current_timestamp(),
        ),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=False, server_default=sa.text("'running'")),
        sa.Column("failure_reason", sa.String(), nullable=True),
        sa.Column("dry_run", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column(
            "triggered_by",
            sa.String(),
            nullable=False,
            server_default=sa.text("'scheduler'"),
        ),
        sa.Column("counts", sa.JSON(), nullable=False, server_default=sa.text("'{}'")),
    )
    op.create_index("ix_runs_started_at", "runs", ["started_at"], unique=False)

    # rate_limit_counters: one row per ISO local-TZ date.
    op.create_table(
        "rate_limit_counters",
        sa.Column("day", sa.String(), primary_key=True, nullable=False),
        sa.Column(
            "submitted_count",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
        ),
    )


def downgrade() -> None:
    op.drop_table("rate_limit_counters")
    op.drop_index("ix_runs_started_at", table_name="runs")
    op.drop_table("runs")
    op.drop_index("ix_secrets_name", table_name="secrets")
    op.drop_table("secrets")
    op.drop_table("settings")
